### ISSUE TITLE
Flare backend version

### ISSUE THREAD

**Issue by joneshf** [purescript/trypurescript#103]
The flare backend appears to be on version `3.0.0`.

The bower says it's using `3.2.0`: https://github.com/purescript/trypurescript/blob/ebf1a244cd2b58d115d56378cb4ab9716da4e3cf/bower.json#L27. `textarea` was added in `3.1.0`: https://github.com/sharkdp/purescript-flare/releases/tag/v3.1.0 (and still exists in `3.2.0`: https://pursuit.purescript.org/packages/purescript-flare/3.2.0/docs/Flare#v:textarea). But if you try to import `textarea`, it fails: http://try.purescript.org/?gist=a02503ed103a29e8212811b5140ecda0.

I'm not sure what to do to fix it or I would have sent a PR.

**Comment by paf31** [comment]
That's actually not the right `bower.json` file. I just use that to generate the license file.

I'll update it now, thanks.

**Comment by paf31** [comment]
I had to roll this back unfortunately. Try Flare has been running on psc 0.10.5 for some time. The bower.json and examples need to be updated to the latest version before I can upgrade.

**Comment by joneshf** [comment]
I'm down to submit a PR, but I don't know what to do.

**Comment by paf31** [comment]
Great :) So to get it running locally you need to [follow these instructions](https://github.com/purescript/trypurescript#configuration), and I usually use a little `python` HTTP server locally to serve the client, but you can use anything. Then if you point the client at `localhost`, you should be good, and you can just tinker with the `bower.json` file and examples locally.

I'd like to move it to `psc-package` though, ideally.

**Comment by joneshf** [comment]
Which branch is that supposed to be on?

**Comment by paf31** [comment]
The client is on `gh-pages`.

**Comment by joneshf** [comment]
Sorry, I can't figure this out :(.

**Comment by sharkdp** [comment]
> Sorry, I can't figure this out :(.

Me neither :confused:

**Comment by rintcius** [comment]
@joneshf @sharkdp 
Regarding development of trypurescript, I have added some notes here: https://gist.github.com/rintcius/c11102b0fe01ba8eecfbb44bcf4da491
(I am using `alias httpserver='python -m SimpleHTTPServer'`)

Step 1, getting the client to work with the standard compile servers on trypurescript, is fairly standard. However getting to work with a local compile server was not that obvious to me.

**Comment by sharkdp** [comment]
@rintcius I was just now struggling with setting all of this up, thank you very much!! This should be in the trypurescript README.

**Comment by rintcius** [comment]
See #109 for readme addition
