### ISSUE TITLE
"Slides" Backend Service Not Available

### ISSUE THREAD

**Issue by alecmerdler** [purescript/trypurescript#116]
### Description

1. Visit http://try.purescript.org
2. Select Backend->Slides

**Console:**
```
POST https://compile.purescript.org/slides/compile 502 (Bad Gateway)
Failed to load https://compile.purescript.org/slides/compile: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 502.
```

**Comment by paf31** [comment]
This is because the server is currently responding with a 500 error to all requests.

**Comment by paf31** [comment]
Fixed, thanks!

**Comment by joncfoo** [comment]
Curious, what was the fix?

**Comment by paf31** [comment]
I was accidentally running the wrong process (wrong PS version) and the server was dying while trying to set up by reading older source files.
