### ISSUE TITLE
Add Aff to Core backend?

### ISSUE THREAD

**Issue by chexxor** [purescript/trypurescript#119]
I found myself wanting to typecheck an Aff code snippet. TryPS doesn't have Aff in the core package-set, which I find a little odd, as several libraries/UI frameworks depend on it.

**Comment by paf31** [comment]
It's not in the core libraries, but it's in the Thermite set already.

**Comment by chexxor** [comment]
Oh my, I did a code search on this repo for aff, but it didn't find that. I'll just close this for now, then.

A sidetrack thought - It's a _bit_ of a pain managing multiple backends. It would be nice to remove the need for isolated backends, and instead just support dynamic importing in the browser from a single set of supported modules. Might be able to use ES6 modules for that - I'm not familiar with trypurescript codebase, so I can't vet the idea.

**Comment by paf31** [comment]
> It's a bit of a pain managing multiple backends. It would be nice to remove the need for isolated backends, and instead just support dynamic importing in the browser from a single set of supported modules.

This is harder than it sounds. We need the compilation products in memory on the server in order to turn around the result quickly.

The real solution here is something like running the compiler client-side using GHCJS, I think.
