### ISSUE TITLE
Save code buffer

### ISSUE THREAD

**Issue by texastoland** [purescript/trypurescript#12]
Several times I've refreshed the page (<kbd>Super+R</kbd>) instead of opening a new tab (<kbd>Super+T</kbd>) 😭
- Easy fix: ask whether to navigate away from an edited buffer.
- Nice fix: keep active buffer in local storage.

**Comment by paf31** [comment]
:+1: Sounds good.

**Comment by matthieubulte** [comment]
I guess we can close that one now that my PR from today was accepted :)

**Comment by paf31** [comment]
Yes, thanks!
