### ISSUE TITLE
Update to 0.12

### ISSUE THREAD

**Issue by Thimoteus** [purescript/trypurescript#121]
I'd like to take this on, but it should probably wait until the full release (as in after release-candidate period), and there's a non-rc 0.12 package set.

EDIT:

Looking at this more, it seems some dependencies will need to be updated as well. This is a possibly nonexhaustive list:

- [ ] [thermite](https://github.com/paf31/purescript-thermite) and its dependencies:
  - [x] aff
  - [x] coroutines
  - [ ] ~dom~
  - [x] freet
  - [x] profunctor-lenses
  - [x] react-dom
  - [x] react
- [ ] [behaviors](https://github.com/paf31/purescript-behaviors) and its dependencies:
  - [x] ~sets~ ordered-collections
  - [x] filterable
  - [x] nullable
  - [ ] drawing
  - [x] effect
- [ ] flare ([sparkle](https://github.com/sharkdp/purescript-sparkle)) and its dependencies:
  - [x] const
  - [x] exists
  - [x] free
  - [ ] ~graphs~ deprecated, replaced by?
  - [x] profunctor
  - [x] quickcheck
  - [x] semirings
  - [x] validation
- [ ] [mathbox](https://github.com/rintcius/purescript-mathbox) and its dependencies:
  - [x] console
  - [x] foreign
  - [x] free
  - [x] globals
  - [x] nullable
  - [x] ~maps~ ordered-collections
  - [ ] lens
  - [x] either
  - [ ] signal: https://github.com/bodil/purescript-signal/pull/65

**Comment by paf31** [comment]
Great, let me know if I can help!

**Comment by vyorkin** [comment]
Just a quick update:

* `therimite` is not updated to 0.12 yet, but its dependencies are updated: https://github.com/purescript-contrib/purescript-react/pull/149, https://github.com/purescript-contrib/purescript-react-dom/pull/11
* `behaviors` should be ready to go (https://github.com/paf31/purescript-behaviors/pull/38 and `drawing` is updated to 0.12 https://github.com/paf31/purescript-drawing/commit/08280b8e60a8cc77c7feda5bc05398e094610886)
* `sparkle` isn't updated, but `flare` is https://github.com/sharkdp/purescript-flare/pull/30 (v.5.0.0), `sparkle` depends on `flare` v4.1.0
* `lens` is not updated yet

**Comment by srghma** [comment]
can we merge https://github.com/purescript/trypurescript/pull/127 already

**Comment by hdgarrood** [comment]
Resolved by #132 and #136
