### ISSUE TITLE
Unknwon value Set.filter

### ISSUE THREAD

**Issue by nukisman** [purescript/trypurescript#125]
```
module Main where

import Data.Set as Set

f = Set.filter
```
gives error `Unknown value Set.filter`

http://try.purescript.org/?session=b41d7125-008d-3ca9-4a89-400ee47ad740

**Comment by kRITZCREEK** [comment]
Will be fixed with #121

**Comment by hdgarrood** [comment]
I'm going to close this then, since it's already tracked by another issue. Thanks for the report!
