### ISSUE TITLE
Scrap this website and use TIO.run ?

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/trypurescript#130]
Searching through SO for an answer to an unrelated question, i came across a website similar to [REPL.it](https://repl.it/): [TIO run (purescript)](https://tio.run/#purescript)

It currently uses `pulp` as its build tool and I infer that it's using a `0.12.x` release because it's using `Effect` not `Eff`: https://github.com/TryItOnline/tiosetup/blob/master/languages/purescript

The idea I had was to use `spago` instead of `pulp` because spago could be used to get the latest package set, which would provide a good majority of the ecosystem's libraries that are known to compile together.

Thoughts?

**Comment by hdgarrood** [comment]
No, I'd rather not. We have no guarantee that TIO will continue to exist or will continue to support purescript. I don't think there's anything wrong with having both.

**Comment by JordanMartinez** [comment]
As an argument against my idea, Try Purescript actually renders HTML whereas TIO just renders console output. In that way, Try Purescript is superior to that one.

Having both sounds like a more sensible option. Also, I apologize if the title of this issue came off as rude / inconsiderate. I didn't realize it could come off that way until a few minutes after posting it.

**Comment by hdgarrood** [comment]
No worries, I didn't read it that way :)
