### ISSUE TITLE
Put all source files in one branch

### ISSUE THREAD

**Issue by hdgarrood** [purescript/trypurescript#132]
At the moment, the source files for the server are in the `master` branch, but the source files for the frontend are in the `gh-pages` branch (along with the compiled output which is actually used by GH Pages). This has a few drawbacks:

- It's more awkward to clone the repo and get the client side and server side working together locally than it potentially could be if all code were in one branch; you need to have two separate git checkouts, for instance
- It's harder to keep track of which versions of the client are supposed to work with which versions of the server (if all the code were in one branch, it would be safe to assume that the server and client at any given commit are supposed to work together, or we could at least aim for that) 
- We have to check in a ton of compiled JS code alongside the sources for the frontend, which makes PRs difficult to review
- It ties merges to deployments in a way that can be awkward -- for example, if a change to the client has passed review and could be merged but can't be deployed yet, say, because the server needs to be deployed first. Right now I would like to merge #127, but it would break Try PureScript unless we deployed the server at the same time.

I think the last one is the most significant, as I think the way this repo is set up currently is more or less incompatible with the approach we were describing at https://discourse.purescript.org/t/looking-for-new-maintainers-for-purescript-org/1014/25 where we want to be able to automate deployment as much as possible.

If we put the frontend source in `master` alongside the server, I think local development and deployment for Try PureScript could be made a bit simpler: we could have all of the source files for both frontend and backend live in the same branch, and have scripts for local development which compile and run of the app for you. We could then have a separate script which generates the compiled frontend files ready for serving and checks those in on the `gh-pages` branch, so that the `gh-pages` branch would only be used for compiled build artifacts and not source code. (Or alternatively we could just stop using GH pages entirely; the CDN probably isn't giving us all that much benefit since the frontend only needs to be loaded once, more or less. But that's something we can consider separately)

**Comment by kritzcreek** [comment]
According to https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source we could also serve the frontend from the `docs/` folder on the master branch. That way you could have PRs that modify both against the same branch.

**Comment by natefaubion** [comment]
> That way you could have PRs that modify both against the same branch.

I think we still want the ability to merge changes without redeploying them. I think gh-pages is helpful for that at least.

**Comment by hdgarrood** [comment]
I'd really like to keep compiled stuff separate for the sake of diffs.

**Comment by hdgarrood** [comment]
For anyone thinking of picking this up: please start with the purescript source code from #127 as that has already been updated for 0.12.

**Comment by gabejohnson** [comment]
> We could then have a separate script which generates the compiled frontend files ready for serving and checks those in on the `gh-pages` branch, so that the `gh-pages` branch would only be used for compiled build artifacts and not source code.

To be clear, does this include `README.md`, `dependencies.sh`, `CNAME`, etc?

**Comment by gabejohnson** [comment]
> We could then have a separate script which generates the compiled frontend files ready for serving and checks those in on the `gh-pages` branch, so that the `gh-pages` branch would only be used for compiled build artifacts and not source code.

To be clear, does this include `README.md`, `dependencies.sh`, `CNAME`, etc?

**Comment by hdgarrood** [comment]
I think we can wait until after we've got everything set up nicely in the `master` branch to worry about the specifics of what build/deploy scripts we have and how they work.

**Comment by hdgarrood** [comment]
Fixed by #135
