### ISSUE TITLE
Structured error format

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/trypurescript#16]
If we can get the server to produce errors in a structured format instead of just an error message, we'd be able to do fancy things like turn various parts into links which move the editor cursor - for example if the error mentions a line number.
Could possibly have links to Pursuit for mentioned types/terms aswell.  For example, if the error mentions the type `Int`, we could link to https://pursuit.purescript.org/packages/purescript-prim/0.8.0/docs/Prim#t:Int

**Comment by paf31** [comment]
:+1:

**Comment by paf31** [comment]
I think we can have the server return the JSON error format if that helps.

**Comment by paf31** [comment]
We now return the JSON error format and highlight errors, so I'll close this. We can open new issues for more specific features.
