### ISSUE TITLE
Further interaction with Gists

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/trypurescript#17]
- List my PureScript Gists (https://developer.github.com/v3/gists/#list-a-users-gists)
  - load into editor
  - get gist id
- Save Gist
  - as new (https://developer.github.com/v3/gists/#create-a-gist)
  - as update to loaded gist (https://developer.github.com/v3/gists/#edit-a-gist)

**Comment by paf31** [comment]
Sounds good, but how would these show up in the UI?

**Comment by paf31** [comment]
Related: https://www.reddit.com/r/purescript/comments/5crn6y/a_note_of_thanks_for_the_trypurescript_editor/da02ur9/

**Comment by soupi** [comment]
I'm going to start working on this :)

**Comment by paf31** [comment]
I think we should break this up into separate issues now that "Share" works.
