### ISSUE TITLE
Convert from ContT and Ajax FFI to Aff and Affjax

### ISSUE THREAD

**Issue by milesfrain** [purescript/trypurescript#179]
I'm looking into fixing #118 and wondering if it would be good to replace some of the ajax FFI code with the Affjax library.

It's also tempting to write an Affjax replacement that uses `fetch` instead, although I assume the [caniuse numbers for that feature (95%)](https://caniuse.com/#feat=fetch) aren't high enough for TryPurescript.

For reference, there's [`fetch-api`](https://pursuit.purescript.org/packages/purescript-fetch-api/1.0.0), which uses [`node-fetch`](https://www.npmjs.com/package/node-fetch), but there could be an even lighter-weight and dependency-free wrapper for just browsers which uses built-in `window.fetch`.

**Comment by thomashoneyman** [comment]
As far as `fetch` goes, there are bindings in the [purescript-web-fetch](https://github.com/purescript-web/purescript-web-fetch) repository.

**Comment by milesfrain** [comment]
Excellent. I'm so glad I asked. I searched pursuit for fetch, but it doesn't look like web-fetch is tracked there yet.

**Comment by hdgarrood** [comment]
Using `fetch` sounds good to me, especially if we can polyfill it for browsers which don't have it yet.

**Comment by hdgarrood** [comment]
I'd also like to use Aff instead of ContT + Effect

**Comment by natefaubion** [comment]
I think if you're going to switch to Aff, what's wrong with using Affjax?

**Comment by hdgarrood** [comment]
Oh yeah of course, that does make more sense. I guess I would usually default to fetch over affjax because in my experience it seems to work better in node (can't remember the details), but in this case we only need it to work in the browser, so that's irrelevant.

**Comment by milesfrain** [comment]
Affjax seems like the easiest path to success, so I'll go with that.

**Comment by milesfrain** [comment]
For reference, the Affjax changes exist in #192. Here are the relevant files for copy-pasting:
* [API.purs](https://github.com/purescript/trypurescript/blob/871d7b4936022fe9a7e7dac66e7eb621a571b5bb/client/src/Try/API.purs)
* [Gist.purs](https://github.com/purescript/trypurescript/blob/871d7b4936022fe9a7e7dac66e7eb621a571b5bb/client/src/Try/Gist.purs)
* [Loader.purs](https://github.com/purescript/trypurescript/blob/871d7b4936022fe9a7e7dac66e7eb621a571b5bb/client/src/Try/Loader.purs)

**Comment by thomashoneyman** [comment]
This was fixed in #208.
