### ISSUE TITLE
Are development instructions still accurate?

### ISSUE THREAD

**Issue by milesfrain** [purescript/trypurescript#183]
Following these steps: https://github.com/purescript/trypurescript/blob/master/README.md#development

Compilation seems to work, but then nothing is displayed in right pane.

Seems to be due to requesting files that don't exist.

From browser:
```
Request URL: http://localhost:8080/js/output/Data.Foldable/index.js
Request Method: GET
Remote Address: 127.0.0.1:8080
Status Code: 404
```
From `httpserver` logs:
```
127.0.0.1 - - [26/Jun/2020 14:03:21] code 404, message File not found
127.0.0.1 - - [26/Jun/2020 14:03:21] "GET /js/output/Data.Foldable/index.js HTTP/1.1" 404 -
127.0.0.1 - - [26/Jun/2020 14:03:21] code 404, message File not found
127.0.0.1 - - [26/Jun/2020 14:03:21] "GET /js/output/Data.Functor/index.js HTTP/1.1" 404 -
127.0.0.1 - - [26/Jun/2020 14:03:21] code 404, message File not found
127.0.0.1 - - [26/Jun/2020 14:03:21] "GET /js/output/TryPureScript/index.js HTTP/1.1" 404 -
```

There's no `output` directory where it's looking:
```
> ls client/public/js 
frame.js  index.js
```

**Comment by milesfrain** [comment]
Here's one workaround:
```
pushd staging
spago build
popd

pushd client/public/js
ln -s ../../../staging/output output
popd
```

Although I notice that the production instance is grabbing these files via the compiler server, e.g:
https://compile.purescript.org/output/Control.Bind/index.js

So I also tried this edit in `client/config/dev/Try.Config.purs`:
```diff
-loaderUrl = "js/output"
+loaderUrl = "http://localhost:8081/output"
```

But that didn't work out.

**Comment by hdgarrood** [comment]
I think doing a symbolic link is the way to go. As for changing Config.purs: it doesn't really matter whether those files are being grabbed from the compile API host or the web frontend host. If you want to grab them from the compile host then you'll need nginx or something in front of the Haskell backend to do that, which isn't worth the hassle in development, I would say.

**Comment by thomashoneyman** [comment]
@hdgarrood I went to hack on Try PureScript tonight, but following the development instructions:

```sh
git clone git@github.com:purescript/trypurescript.git
cd trypurescript

stack build

# Install PureScript dependencies
cd staging
spago install

stack exec trypurescript 8081 $(spago sources)
# should output that is is compiling the sources (first time)
# then: Setting phasers to stun... (port 8081) (ctrl-c to quit)
```

...produces a ton of "ModuleNotFound" errors in compilation:

```
$ stack exec trypurescript 8081 $(spago sources)
MultipleErrors {runMultipleErrors = [ErrorMessage [ErrorInModule (ModuleName "Test.Abides.Properties"),PositionedError (SourceSpan {spanName = ".spago/abides/v0.0.1/src/Test/Abides/Properties.purs", spanStart = SourcePos {sourcePosLine = 4, sourcePosColumn = 1}, spanEnd = SourcePos {sourcePosLine = 4, sourcePosColumn = 32}} :| [])] (ModuleNotFound (ModuleName "Prelude")),ErrorMessage [ErrorInModule (ModuleName "Test.Abides.Control.Plus"),PositionedError (SourceSpan {spanName = ".spago/abides/v0.0.1/src/Test/Abides/Control/Plus.purs", ...
```

...which continue even if I first run `spago build` to make sure an `output` directory exists in `trypurescript/staging`. Am I missing something simple here?

**Comment by thomashoneyman** [comment]
Oddly enough, I hopped on a call with @milesfrain and running the same set of steps with the same Stack, Spago, etc. versions on his system vs. my system produces a successful build on his and a bunch of `ModuleNotFound` errors on mine. Still digging to see how to resolve this.
