### ISSUE TITLE
Create guide for adding missing shims

### ISSUE THREAD

**Issue by milesfrain** [purescript/trypurescript#188]
We should create a guide on how to add shims to https://github.com/purescript/trypurescript/blob/master/client/src/Try/Shim.purs

Then point to this guide when a shim is not found, as suggested in https://github.com/purescript/trypurescript/pull/187/files#r464147289

**Comment by JordanMartinez** [comment]
AFAIK, this has been documented in the `RELEASE.md` file now that we're using import maps.
