### ISSUE TITLE
can't create a new gist 

### ISSUE THREAD

**Issue by Turatov** [purescript/trypurescript#201]
GIST ERROR: Could Not Create Moi > Reason: Requires authentication   

Help fix it, please ! 

![image](https://user-images.githubusercontent.com/62321124/91682366-230c5a80-eb73-11ea-891c-c676e596b144.png)

**Comment by thomashoneyman** [comment]
This is being updated — see https://try.ps.ai, which previews this. The regular Try PureScript will be updated when we have time.
