### ISSUE TITLE
Update Thermite and Flare data for 0.9 release

### ISSUE THREAD

**Issue by paf31** [purescript/trypurescript#21]
cc @sharkdp

**Comment by paf31** [comment]
The existing services are still running, but will stop working if they get restarted, so we should aim to get the new externs files ready soon.

**Comment by sharkdp** [comment]
I'm on holidays for 2 weeks and won't be able to work on this. Feel free to restart, it's not too bad if try flare won't work for some time..

**Comment by paf31** [comment]
Ah ok, no rush. Once I get Thermite done, I can probably get the externs built myself, you would just need to update your examples.

**Comment by paf31** [comment]
Thermite is updated. 

@sharkdp I can create the assets for Try Flare if you like. What libraries are needed? Just `purescript-flare`?

**Comment by sharkdp** [comment]
I'm not sure anymore, and I cannot check it right now. If I recall
correctly, I installed flare, flarecheck and a lot of the standard
libraries like arrays, strings, foldable-traversable, .. but most of them
should be dependencies of flare(check) anyway.
Am 21.06.2016 21:32 schrieb "Phil Freeman" <notifications@github.com>:

**Comment by paf31** [comment]
@sharkdp The new API is live at https://compile.purescript.org/flare2
