### ISSUE TITLE
Update Try PureScript for 0.14

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/trypurescript#210]
Once the 0.14 package set has been released, we'll need to:

- Update the package sets in use in this repository
- Verify that the package set behaves properly in Try PureScript
- Perform any other last-minute checks

Three checks we should definitely complete before deploying a new version on the new package set:

- [ ] Verify that newtypes with their constructors in scope only for a coercion do not produce warnings
- [ ] Verify pattern guards are handled correctly (see https://github.com/purescript/purescript/pull/2801)
- [x] Verify all of the Try PureScript examples continue to behave correctly with the new package set.
- [x] Verify that the new package set won't overwhelm the memory in the server, and add the steps to check this to the maintainers' documentation.

**Comment by JordanMartinez** [comment]
Can this issue be closed now?
