### ISSUE TITLE
Usage of React.Basic.Hooks is broken

### ISSUE THREAD

**Issue by ptrfrncsmrph** [purescript/trypurescript#236]
Usage of `React.Basic.Hooks` (for example, the minimal [HelloReactHooks](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/HelloReactHooks/src/Main.purs) recipe from the [`purescript-cookbook`](https://github.com/JordanMartinez/purescript-cookbook)) throws an error
```
Uncaught TypeError: React.forwardRef is not a function
```

**Comment by ptrfrncsmrph** [comment]
Fixed by #237

**Comment by thomashoneyman** [comment]
This has been deployed as of:
https://github.com/purescript/trypurescript/releases/tag/v2021-07-04.1
