### ISSUE TITLE
Scrolling past the end

### ISSUE THREAD

**Issue by rightfold** [purescript/trypurescript#26]
It would be nice if you could scroll past the end in the text editor so that you don't have to bend your neck down when editing the last few lines in a large file. ST3, Vim, Emacs and Visual Studio have similar behavior.

Example:
![screenshot](https://cloud.githubusercontent.com/assets/5132125/17077228/85c55ba8-50c8-11e6-9e4d-692b55f699c8.PNG)

**Comment by paf31** [comment]
There is probably an Ace setting for this.

**Comment by paf31** [comment]
Fixed
