### ISSUE TITLE
How to deal with warnings in examples?

### ISSUE THREAD

**Issue by andys8** [purescript/trypurescript#283]
This is a minor issue. I was wondering if we can or should address warnings shiowing up in the [default examples](https://github.com/purescript/trypurescript/tree/master/client/examples).

## Warnings

![image](https://user-images.githubusercontent.com/13085980/178459549-b6bff22a-a7a0-45ca-a27d-fb30664d4cd2.png)

![image](https://user-images.githubusercontent.com/13085980/178459715-e6f02e1f-2537-4180-a9b5-447e8b4cc407.png)

![image](https://user-images.githubusercontent.com/13085980/178459872-ac2f7fbe-0d9c-483e-9484-5da1b2bd35dd.png)

## Options

* Keep the examples as they are and show the warnings
* Change the code examples (e.g. add type annotation to `main`)
* Change Try-PureScript to hide these specific warnings (main type signature, TryPureScript import)

**Comment by JordanMartinez** [comment]
We should update the examples so that the warnings no longer appear.

**Comment by andreas-ebot7** [comment]
Adressed in https://github.com/purescript/trypurescript/pull/286/files

**Comment by andys8** [comment]
Addressed in  https://github.com/purescript/trypurescript/pull/286
