### ISSUE TITLE
typeclasses example generates JS with ReferenceError

### ISSUE THREAD

**Issue by michaelficarra** [purescript/trypurescript#4]
The typeclasses example (http://try.purescript.org/example/typeclasses) generates JS that begins with

```js
var PS = PS || {};
PS.Prelude = (function () {
    "use strict";
    return {
        "++": $plus$plus
    };
})();
var PS = PS || {};
PS.Main = (function () {
    "use strict";
    ...
```

which will throw a ReferenceError for `$plus$plus`. This code isn't even used, since Semigroup `++` on strings is compiled straight to JavaScript `+`.

**Comment by paf31** [comment]
Yes, it's an unfortunate artifact of the way I do dead code elimination. I think I'd like to stop showing the generated code, and just provide a way to run it in an iframe instead, like Luite's Try PureScript in GHCJS.

**Comment by michaelficarra** [comment]
Link?

**Comment by paf31** [comment]
http://hdiff.luite.com/tmp/try-purescript.jsexe/
