### ISSUE TITLE
Flare CSS problems

### ISSUE THREAD

**Issue by soupi** [purescript/trypurescript#44]
@sharkdp  First of all I wanted to say flare still looks awesome!

I have noticed a few CSS problems in the try purescript site:

1. in the temperature example the temperature picker goes over the temperature label (probably because the width for it is 100px). Perhaps a putting the components in a table will work?
2. Components like the font size for the title or hue and radius in the drawing example are invisible to me. I can manipulate them if i press where they are supposed to be but i can't see them.

This is using Firefox 50.

edit: I can, however, see the sliders for hue and radius fine on my phone (also firefox).

**Comment by sharkdp** [comment]
Thanks for the notice, I should have checked everything with Firefox. The slider problem was fixed a while back here:

https://github.com/sharkdp/purescript-flare/pull/16

... but I forgot to include it in try-flare. I opened a PR: #46

**Comment by soupi** [comment]
Thanks, the sliders are visible now!

But regarding labels, is it ok to limit them to 150px?

**Comment by sharkdp** [comment]
> But regarding labels, is it ok to limit them to 150px?

Do you still see any problems with the wider labels? I know it's not the best solution, but using a table would require a rewrite of the internals of Flare..

**Comment by soupi** [comment]
I see. alright. I just thought that someone might want to use a bigger font for the word temperature or maybe a longer word than that and that would be a problem. but i guess it's ok if it's more trouble than worth :)
