### ISSUE TITLE
Mathbox backend?

### ISSUE THREAD

**Issue by rintcius** [purescript/trypurescript#56]
I'm working on a [mathbox](https://github.com/rintcius/purescript-mathbox) backend for trypurescript (got a first version working locally). Is there interest (and server resources) to add it to http://try.purescript.org/ ?

**Comment by paf31** [comment]
If you can provide the list of dependencies, I can create the server instance.

**Comment by rintcius** [comment]
Great!

I'm using `purescript-mathbox` `v0.1.0` with these deps https://github.com/rintcius/purescript-mathbox/blob/v0.1.0/bower.json#L15-L27

Let me know if you need more info.

I'll probably also need to create a `TryMathbox`. Is the idea to add that to https://github.com/purescript/trypurescript/tree/master/staging a la `TryPurescript`? (asking because only `core` backend has something there at the moment).

**Comment by paf31** [comment]
The server is running [here](https://compile.purescript.org/purescript-mathbox).

I didn't include `purescript-mathbox` itself yet. Should I use 0.1.0?

**Comment by paf31** [comment]
> I'll probably also need to create a TryMathbox

Please just make a PR on the `gh-pages` branch with your changes. Later, I hope we can use `staging/` to contain package set definitions, so that these sorts of changes can be more easily automated. But for now, I'm just using Bower or psc-package to set things up manually.

**Comment by paf31** [comment]
Ok, the bundle should now contain `purescript-mathbox` itself.

Please let me know if you need me to deploy any additional modules.

**Comment by rintcius** [comment]
That's quick, thanks!
