### ISSUE TITLE
Get rid of initial snippets

### ISSUE THREAD

**Issue by rintcius** [purescript/trypurescript#58]
As discussed in https://github.com/purescript/trypurescript/pull/57 the plan is to get rid of initial snippets. It would be good if the maintainers of the backends would create an initial gist  (so that they have ownership of it) & include it here.

After we have all the gists we can get rid of the initial snippets.

@soupi already provided gist for purescript-slides: c62b5778a6a5f2bcd32dd97b294c068a.

**Comment by paf31** [comment]
Core: b57a766d417e109785540d584266fc33
Thermite: 85383bb058471109cfef379bbb6bc11c

cc @sharkdp Could you please create one for Try Flare?

**Comment by sharkdp** [comment]
Of course, sorry for the delay.

Flare: 4f54d6dd213caa54d736ead597e17fee

**Comment by rintcius** [comment]
@paf31 Could you add Mathbox to `Core: b57a766d417e109785540d584266fc33`?

@soupi The image in slides demo is broken `purescript-slides: c62b5778a6a5f2bcd32dd97b294c068a`

**Comment by paf31** [comment]
@rintcius I already added a link to my Gist.

**Comment by rintcius** [comment]
@paf31 Ah I should have looked at it while testing the PR

**Comment by soupi** [comment]
@rintcius  thanks for noticing. should be fixed now.
