### ISSUE TITLE
Update UX to be more code focused

### ISSUE THREAD

**Issue by codygman** [purescript/trypurescript#6]
Keep the examples and keep the theme consistent with purescript.org, but maybe draw inspiration from the [go playground](http://play.golang.org/). As you can see most of the space is taken up by the code editor, some by the output window, and a small space at the top for related functions.

I think the examples could be a dropdown in the top bar. Perhaps we could even have a "play.purescript.org" which offers the same functionality of running code and sharing snippets.

**Comment by paf31** [comment]
:+1: to all of this. Ideally, I'd like to hand this project off to someone else for maintainance at this point, since I don't really have time to implement these things.

**Comment by paf31** [comment]
How do you like the new version?

**Comment by AppShipIt** [comment]
I'm interested in helping but only after trying [iPython integration](https://github.com/notablemind/jupyter-nodejs/tree/master/ext). It'd ultimately be nicer for documentation purposes.

**Comment by texastoland** [comment]
I ended up being introduced to the guy who made [Plunker](https://github.com/ggoodman/plunker-run) (multiple file support and beautiful package search) which was a much better fit than JSBin and [Mancy](https://github.com/princejwesley/Mancy) (which your recent REPL socket may help) is a better fit than iPython.
