### ISSUE TITLE
Not clear how to get dist/

### ISSUE THREAD

**Issue by lazywithclass** [purescript/trypurescript#64]
Hey, thanks for this first of all!

I am having some problems getting to the point where I can run [the example command you provided](https://github.com/purescript/trypurescript#example).

`$ cabal --version` gives me

> cabal-install version 1.22.9.0
> using version 1.22.8.0 of the Cabal library 

I had to install the following packages

```
$ cabal install glob aeson http-types purescript scotty
```

Then I've run

```
$ cabal install
# takes quite some time, then I clearly see it doing
Downloading purescript-0.10.5...
Configuring purescript-0.10.5...
Building purescript-0.10.5...
# some more output
```

When I execute `$ cabal run` I get 

> Preprocessing executable 'trypurescript' for trypurescript-0.10.5...
> Linking dist/build/trypurescript/trypurescript ...
> Running trypurescript...
> trypurescript: user error (Pattern match failure in do expression at server/Main.hs:164:3-27)

I know next to nothing about Haskell or PureScript, any help would be greatly appreciated!

UPDATE

I figured out I don't need to run `cabal run`, I just have to run the command from dist/, nevermind, are you willing to take a PR with some detailed instructions on how to use this from a newbie point of view?

**Comment by soupi** [comment]
### Running try-purescript without a local backend

1. Switch to the `gh-pages` branch
2. Use an http server to serve try-purescript (example: `python -m SimpleHTTPServer` or `http-server -p 3000`)
3. Open your browser at http://localhost:8000 (or whichever port you used to serve) and you should see the try-purescript app

### Running try-purescript with a local backend

Use the [Haskell Stack](http://haskell-lang.org/get-started) build tool to build the backend:

- Clone the repo
- Run `stack build` (you might also need `--install ghc`)

Install the core try-purescript packages:

```sh
(cd staging/core && psc-package update)
```

You might need to change the version in `psc-pacakge.json` to the current compiler version installed on your machine (for example: `"set": "psc-0.10.5"`)

After that you can run the server with:

```sh
stack exec trypurescript -- 3333 staging/core/.psc-package/psc-0.10.4/*/*/src/**/*.purs staging/core/src/TryPureScript.purs
```

You will also need to change the endpoint for core to point to your local backend:

1. Switch again to `gh-pages`
2. Change [this line](https://github.com/purescript/trypurescript/blob/gh-pages/js/index.js#L95) to:

```js
 endpoint: "http://localhost:3333",
```

or similar

Actually, it will be easier to just clone the repo twice and keep one branch on `master` for the backend and one branch on `gh-pages` for the frontend.

Hope this helps.

**Comment by lazywithclass** [comment]
That's great! So I don't really need a server, I could host the static files on S3 or the likes and go from there.

Thank you so much for this @soupi, is it already written somewhere or what about adding it to the README?

**Comment by soupi** [comment]
What is your use case? we might be able to help more if we knew what you are trying to do :)

I can PR this if @paf31 wants it.

**Comment by lazywithclass** [comment]
Ah yes sure! So I'm at Recurse Center (https://www.recurse.com/), me and a fellow recurser with Haskell experience are trying to come up with an online interactive website that could teach fundamental principles of functional programming in a typed language, for newbies like myself :D

**Comment by soupi** [comment]
Good luck! If you have further questions on PureScript specifically you might want to ask in IRC/Slack/Reddit/Mailing list where it'll get better exposure.

Also, you might also want to check [Code World](https://code.world/) as well as you might have similar goals :)

**Comment by lazywithclass** [comment]
Thanks for the tip and for the help, really appreciated @soupi :)

**Comment by lazywithclass** [comment]
@soupi I forgot about to ask (and sorry if this is not the best place), if it's ok to make calls to try.purescript.org to get back results in our project, which is all about learning functional programming using PureScript.

We don't expect to hammer it at all, both because we won't be showing the project a lot in the beginning and both because we call the endpoint on a specific key combination, not on onchange.

Please let me know your thoughts, and thanks again for your efforts on PureScript!

**Comment by soupi** [comment]
Best to ask @paf31 this kind of question :)

**Comment by paf31** [comment]
@lazywithclass Go for it :) Please let me know if you expect the usage to increase a lot, but for moderate use, that's what it's there for.

**Comment by lazywithclass** [comment]
@paf31 that's great thanks! Yes, I will definitely come back if our project grows in terms of usage.
