### ISSUE TITLE
iOS: code pane cut off

### ISSUE THREAD

**Issue by liammcdermott** [purescript/trypurescript#71]
When using iOS to view try.purescript.org the bottom of the coding pane is cut off at the bottom of the viewport, if there's more code than will fit in the pane it is cut off and no vertical scroll bar is displayed, scrolling does not work.

Additionally, tapping to set the focus in the box works (as does typing normal characters into that box), however the arrow keys on an iPad keyboard (physical) do not function: pressing them has no effect.

**Comment by soupi** [comment]
ace editor support is not very good on mobile but it does somewhat work. To scroll you really need to try scrolling on the right side of the screen near the end.

I asked to use a friend's iphone to see how it works but haven't seen any different behaviour. could you perhaps include a short video or a screenshot of the behaviour you experience?

**Comment by paf31** [comment]
Will be fixed by #98
