### ISSUE TITLE
"File named Main.purs does not exist" error should be shown to the user

### ISSUE THREAD

**Issue by paulyoung** [purescript/trypurescript#76]
I tried constructing a URL using the ID of my own secret gist.

I see the following:

```
Error 1 of 1

  Unable to parse module:
  unexpected end of input
```

**Comment by paulyoung** [comment]
I opened the console and saw this in the browser: `File named Main.purs does not exist in gist`

I renamed the file, and after a few minutes things started working as expected.

It would be great if this error message was more visible 😄

**Comment by soupi** [comment]
We should also update the Help to specify that.

**Comment by paf31** [comment]
This should be a simple fix, if someone wants to take it.

**Comment by paf31** [comment]
Fixed
