### ISSUE TITLE
add purescript-validation to thermite engine?

### ISSUE THREAD

**Issue by sudhirvkumar** [purescript/trypurescript#91]
`purescript-validation` package is available in the `core` engine.

Can we also add that to `thermite` engine?

**Comment by paf31** [comment]
Should be fairly simple. Would you like to try it out and make a PR?

**Comment by sudhirvkumar** [comment]
@paf31 with my limited understanding. I don't think the packages for the engines are part of the repo. If you can point me in the right direction. I would be happy to send you a PR
